"""SQLAlchemy ORM models — the database tables for Sentinel.

Why do we need database models separate from Pydantic schemas?
==============================================================
Pydantic schemas (in ``core/schemas.py``) define the *API contract* —
what data looks like when it enters or leaves the system via HTTP.

SQLAlchemy models define the *database contract* — how data is stored
in PostgreSQL tables with indexes, constraints, and relationships.

They look similar but serve different purposes:
- Pydantic: validation, serialization, API docs
- SQLAlchemy: SQL generation, migrations, query building

Table Design:
- ``alert_events``: Stores every alert generated by the detection pipeline.
  Indexed by ``src_ip``, ``severity``, and ``created_at`` for fast dashboard queries.
- ``log_events``: Optional archival table for raw log events (can be toggled).
  Useful for forensic analysis after an alert fires.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Base class for all SQLAlchemy models.

    Using DeclarativeBase (SQLAlchemy 2.0 style) instead of the old
    declarative_base() function. This gives us better type checking
    and IDE support.
    """


class AlertEvent(Base):
    """A security alert generated by the detection pipeline.

    One row is created each time the ML engine or rule engine flags
    an event as suspicious. Fields mirror ``AlertRecord`` in schemas.py
    but are mapped to PostgreSQL columns with proper types and indexes.

    Attributes:
        id: Auto-incrementing primary key (internal use only).
        alert_id: UUID exposed to the API (stable external identifier).
        event_id: The original LogEvent.event_id that triggered this alert.
        created_at: When the alert was created (server-side default).
        src_ip: Attacker source IP address.
        event_type: Classification (ssh_brute_force, sqli_attempt, etc.).
        severity: Alert level (low, medium, high, critical).
        anomaly_score: ML engine score (-1.0 to +1.0).
        rule_matched: ID of the YAML rule that triggered (if any).
        rca: Root cause analysis text from the LLM.
        mitre_attack_id: MITRE ATT&CK technique ID (e.g. T1110.001).
        mitre_technique: Human-readable technique name.
        remediation: List of remediation steps (stored as JSONB array).
        is_blocked: Whether the IP was auto-blocked.
        raw_event: Full original log event stored as JSONB for forensics.
    """

    __tablename__ = "alert_events"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )
    alert_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        default=lambda: str(uuid.uuid4()),
        unique=True,
        nullable=False,
        index=True,
    )
    event_id: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )
    src_ip: Mapped[str] = mapped_column(
        String(45),  # IPv6 max length
        nullable=False,
        index=True,
    )
    event_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )
    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="medium",
    )
    anomaly_score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )
    rule_matched: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )
    rca: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )
    mitre_attack_id: Mapped[str | None] = mapped_column(
        String(30),
        nullable=True,
    )
    mitre_technique: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
    )
    remediation: Mapped[list[str] | None] = mapped_column(
        ARRAY(Text),
        nullable=True,
        default=list,
    )
    is_blocked: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )
    raw_event: Mapped[dict | None] = mapped_column(  # type: ignore[type-arg]
        JSONB,
        nullable=True,
    )

    # Composite indexes for common dashboard queries:
    # "Show me all CRITICAL alerts from the last hour"
    __table_args__ = (
        Index("ix_alert_severity_created", "severity", "created_at"),
        Index("ix_alert_src_ip_created", "src_ip", "created_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<AlertEvent(alert_id={self.alert_id!r}, "
            f"severity={self.severity!r}, src_ip={self.src_ip!r})>"
        )
