"""create alert_events table

Revision ID: 001_initial
Revises:
Create Date: 2026-10-08

Creates the ``alert_events`` table for storing security alerts
generated by the ML engine and rule engine detection pipeline.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

# Revision identifiers
revision: str = "001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create alert_events table with indexes."""
    op.create_table(
        "alert_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("alert_id", postgresql.UUID(as_uuid=False), nullable=False),
        sa.Column("event_id", sa.String(64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("src_ip", sa.String(45), nullable=False),
        sa.Column("event_type", sa.String(50), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("anomaly_score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("rule_matched", sa.String(100), nullable=True),
        sa.Column("rca", sa.Text(), nullable=True),
        sa.Column("mitre_attack_id", sa.String(30), nullable=True),
        sa.Column("mitre_technique", sa.String(200), nullable=True),
        sa.Column("remediation", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("is_blocked", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("raw_event", postgresql.JSONB(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Individual indexes for filtered queries
    op.create_index("ix_alert_events_alert_id", "alert_events", ["alert_id"], unique=True)
    op.create_index("ix_alert_events_event_id", "alert_events", ["event_id"])
    op.create_index("ix_alert_events_created_at", "alert_events", ["created_at"])
    op.create_index("ix_alert_events_src_ip", "alert_events", ["src_ip"])

    # Composite indexes for common dashboard queries
    op.create_index("ix_alert_severity_created", "alert_events", ["severity", "created_at"])
    op.create_index("ix_alert_src_ip_created", "alert_events", ["src_ip", "created_at"])


def downgrade() -> None:
    """Drop alert_events table and all indexes."""
    op.drop_index("ix_alert_src_ip_created", table_name="alert_events")
    op.drop_index("ix_alert_severity_created", table_name="alert_events")
    op.drop_index("ix_alert_events_src_ip", table_name="alert_events")
    op.drop_index("ix_alert_events_created_at", table_name="alert_events")
    op.drop_index("ix_alert_events_event_id", table_name="alert_events")
    op.drop_index("ix_alert_events_alert_id", table_name="alert_events")
    op.drop_table("alert_events")
